config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "welcome#index"
  devise_for :users, skip: [:registrations]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :reports, only: [:index, :new, :create]
  resources :videos, only: [:index, :new, :create]
  resources :sites, only: [:index, :new, :create]

  resource :about, only: [:show]

  resources :list_views, only: [:index]

  resources :developer_guides, only: [:index]

  resource :setting, except: [:destroy]
end

app/models/video.rb
# frozen_string_literal: true

class Video < ApplicationRecord
  validates :title, :author, :url, presence: true
  validates :url, uniqueness: true
end

app/controllers/videos_controller.rb
class VideosController < AdminController
  def index
    @videos = Video.all.order(:display_order)
  end

  def new
  end

  def create
    tempfile = file_params[:file]
    ::VideoImportService.process(tempfile.path)

    redirect_to videos_path, notice: "Videos are successfully imported"
  end

  private
    def file_params
      params.require(:videos).permit(:file)
    end
end

app/views/videos/index.html.erb
<div class="mt-3">
  <%= link_to "New videos", new_video_path, class: "btn btn-primary float-right" %>
  <h2>Videos: <b><%= @videos.count %></b></h2>
</div>

<% i = 0 %>
<table class="table">
  <tr>
    <th>#</th>
    <th>Title</th>
    <th>Author</th>
    <th>Url</th>
  </tr>

  <% @videos.each do |video| %>
    <tr>
      <td><%= i+=1 %></td>
      <td><%= video.title %></td>
      <td><%= video.author %></td>
      <td><%= link_to video.url, video.url, target: "_blank", rel: "noopener" %></td>
    </tr>
  <% end %>
</table>

app/views/videos/new.html.haml
.d-flex.justify-content-center.align-items-center.vh-100
  .card
    .card-header 
      %h5 Choose videos
    .card-body
      = simple_form_for :videos, url: videos_path do |f|
        = f.input :file, as: :file, label: false
        = f.submit "Upload", class: "btn btn-primary"