config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "welcome#index"
  devise_for :users, skip: [:registrations]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :reports, only: [:index, :new, :create]
  resources :videos, only: [:index, :new, :create]
  resources :sites, only: [:index, :new, :create]

  resource :about, only: [:show]

  resources :list_views, only: [:index]

  resources :developer_guides, only: [:index]

  resource :setting, except: [:destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/faq.rb
# frozen_string_literal: true

class Faq < ApplicationRecord
  acts_as_list

  before_create :set_position

  private
    def set_position
      self.position = Faq.maximum(:position).to_i + 1
    end
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  validates :code, :name_en, :name_km, :kind, presence: true
  validates_inclusion_of :kind, in: %w[province district commune village], message: "type %{value} is invalid"
  validates :latitude, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }, allow_blank: true
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }, allow_blank: true
  validate :presence_of_lat_lng

  has_many :children, class_name: "Location", foreign_key: :parent_id
  belongs_to :parent, class_name: "Location", optional: true

  def latlng
    [latitude, longitude]
  end

  def self.location_kind(code)
    return if code.blank?

    case code.to_s.length
    when 2
      "province"
    when 4
      "district"
    when 6
      "commune"
    else
      "village"
    end
  end

  private
    def presence_of_lat_lng
      return unless latitude.present? != longitude.present?

      errors.add(:longitude, "can't be blank") if latitude.present?
      errors.add(:latitude, "can't be blank") if longitude.present?
    end
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  has_many :report_details, dependent: :destroy

  validates :location_code, presence: true
  validates :location_code, uniqueness: true
  validates :total_case, numericality: { greater_than_or_equal_to: 0 }
  validates :new_case, numericality: { greater_than_or_equal_to: 0 }
  validates :new_recovered_case, numericality: { greater_than_or_equal_to: 0 }
  validates :new_death_case, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :location, class_name: "Location", foreign_key: "location_code"

  def self.has_detail?
    ReportDetail.count > 0
  end
end

app/models/report_detail.rb
class ReportDetail < ApplicationRecord
  belongs_to :report

  validates :field_name, :field_value, presence: true
  validates :display_order, numericality: { greater_than: 0 }
end

app/models/setting.rb
# frozen_string_literal: true

class Setting < ApplicationRecord
    def self.marker_radius_baseline
        ENV.fetch('MAP_MARKER_RADIUS_BASELINE') { 100 }.to_i
    end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :validatable
end

app/models/video.rb
# frozen_string_literal: true

class Video < ApplicationRecord
  validates :title, :author, :url, presence: true
  validates :url, uniqueness: true
end

app/controllers/abouts_controller.rb
# frozen_string_literal: true

class AboutsController < ApplicationController
  def show
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"

  before_action :authenticate_user!
end

app/controllers/faq_admins_controller.rb
# frozen_string_literal: true

class FaqAdminsController < AdminController
  def index
    @faqs = Faq.order(:position)
  end

  def new
    @faq = Faq.new
  end

  def create
    @faq = Faq.new(faq_params)

    if @faq.save
      redirect_to faq_admins_path,  flash: { notice: "Faq has been created." }
    else
      flash.now[:alert] = @category.errors.full_messages
      render :new
    end
  end

  def edit
    @faq = Faq.find(params[:id])
  end

  def update
    @faq = Faq.find(params[:id])

    if @faq.update(faq_params)
      redirect_to faq_admins_path,  flash: { notice: "Faq has been updated." }
    else
      flash.now[:alert] = @category.errors.full_messages
      render :edit
    end
  end

  def destroy
    @faq = Faq.find(params[:id])
    if @faq.destroy
      flash.now[:notice] = "Faq has been deleted."
    else
      flash.now[:alert] = @category.errors.full_messages
    end

    redirect_to faq_admins_path
  end

  private
    def faq_params
      params.require(:faq).permit(:id, :question_km, :question_en, :answer_km, :answer_en)
    end
end

app/controllers/faqs_controller.rb
# frozen_string_literal: true

class FaqsController < ApplicationController
  def index
    @faqs = Faq.order(:position)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @reports = Report.includes(:location, :report_details).order("total_case desc, updated_at desc").all
    @json_reports = @reports.to_json(include: { location: { only: [:name_km, :latitude, :longitude] }, report_details: { only: [:field_name, :field_value] } })
    @summary_report = summary_report
    @json_summary_report =summary_report.to_json(include: { location: { only: [:name_km, :latitude, :longitude] } })
    @has_detail_info = Report.has_detail?
    @videos = Video.order(:display_order)
    @setting = Setting.first || Setting.new
  end
end

app/controllers/reports_controller.rb
class ReportsController < AdminController
  def index
    @cols = ReportDetail.order(display_order: :asc).pluck(:field_name).uniq
    @reports = Report.includes(:report_details)
  end

  def new
  end

  def create
    tempfile = file_params[:file]
    ::ReportImportService.process(tempfile.path)

    redirect_to reports_path, notice: "successfully imported"
  end

  private
    def file_params
      params.require(:reports).permit(:file)
    end
end

app/controllers/settings_controller.rb
# frozen_string_literal: true

class SettingsController < AdminController
  def show
    @setting = Setting.first
  end

  def new
    @setting = Setting.new
  end

  def create
    @setting = Setting.new(setting_params)

    if @setting.save
      redirect_to setting_path
    else
      flash.now[:alert] = @sop.errors.full_messages
      render :new
    end
  end

  def edit
    @setting = Setting.first
  end

  def update
    @setting = Setting.first

    if @setting.update(setting_params)
      redirect_to setting_path
    else
      flash.now[:alert] = @sop.errors.full_messages
      render :edit
    end
  end

  private
    def setting_params
      params.require(:setting).permit(:last_updated)
    end
end

app/controllers/videos_controller.rb
class VideosController < AdminController
  def index
    @videos = Video.all.order(:display_order)
  end

  def new
  end

  def create
    tempfile = file_params[:file]
    ::VideoImportService.process(tempfile.path)

    redirect_to videos_path, notice: "Videos are successfully imported"
  end

  private
    def file_params
      params.require(:videos).permit(:file)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < HomeController
  def index
    super
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def css_class_name
    prefix = params["controller"].downcase.split("/").join("-")
    subfix = params["action"]

    "#{prefix}-#{subfix}"
  end

  def get_css_active_class(name)
    return "active" if params["controller"] == name
  end

  def active_case(report)
    report.total_case.to_i - report.recovered_case.to_i - report.death_case.to_i
  end

  def mobile_request?
    params[:display_mode] != "desktop" && (@device.device_type == "smartphone" || @device.device_type == "phablet")
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
  def youtube_thumbnail(url)
    id = get_youtube_id(url)
    "https://img.youtube.com/vi/#{id}/mqdefault.jpg"
  end

  private
    def get_youtube_id(url)
      url = url.gsub(/(>|<)/i, "").split(/(vi\/|v=|\/v\/|youtu\.be\/|\/embed\/)/)
      url[2].present? ? url[2].split(/[^0-9a-z_\-]/i)[0] : url
    end
end

app/helpers/setting_helper.rb
module SettingHelper
end

app/views/shared/_admin_navbar.html.haml
= link_to "ជំងឺឆ្លង COVID-19", reports_path, class: "navbar-brand"
%button.navbar-toggler{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavDropdown", "data-toggle" => "collapse", :type => "button"}
  %span.navbar-toggler-icon
#navbarNavDropdown.collapse.navbar-collapse
  %ul.navbar-nav.mr-auto
    %li.nav-item{ class: ("active" if current_page?(reports_path)) }
      = link_to "Reports", reports_path, class: "nav-link"
    %li.nav-item{ class: ("active" if current_page?(videos_path)) }
      = link_to "Videos", videos_path, class: "nav-link"
    %li.nav-item{ class: ("active" if current_page?(setting_path)) }
      = link_to "Setting", setting_path, class: "nav-link"
  = link_to "Sign out", destroy_user_session_path, method: :delete, data: { confirm: "Sign out?" }, class: 'btn btn-dark'

app/views/shared/_mobile_nav_bar.html.haml
.mobile-header
  .a.logo
  .mobile-menu-button
    %i.fa.fa-bars

.mobile-menu-panel{ style: "display: none;" }
  .overlay
  .mobile-menu.d-flex.flex-column
    %a.close-button
      %i.fa.fa-times

    .menu-options
      = link_to "#", class: "menu-option btn-share" do
        %i.fas.fa-share-square
        %div ចែករំលែក

      = link_to developer_guides_path(display_mode: params[:display_mode]), class: "menu-option" do
        %i.fa.fa-code
        %div Developer Guide

      = link_to about_path(display_mode: params[:display_mode]), class: "menu-option" do
        %i.fa.fa-info-circle
        %div អំពីកម្មវិធី

    %small.text-center.mt-3= "(#{@setting.last_updated})"

    .flex-grow-1.d-flex.align-items-end
      .d-flex.w-100
        %small.flex-grow-1
          = "#{t('shared.number_of_visitor')}: #{number_to_human(Ahoy::Visit.count, :format => '%n%u', :units => { :thousand => 'K' })}"

        %small= "#{t('shared.version')}: #{ENV.fetch('APP_VERSION') { 'development' }}"

app/views/shared/_notify_message.html.haml
- if flash[:notice]
  .alert.alert-success.notify-message
    %button.close{type: 'button', 'data-dismiss' => 'alert', 'aria-label' => 'Close'}
    = flash[:notice]
- if flash[:alert]
  .alert.alert-danger.notify-message
    %button.close{type: 'button', 'data-dismiss' => 'alert', 'aria-label' => 'Close'}
    = flash[:alert]

:javascript
  setTimeout(function() {
    $( ".alert" ).fadeOut( "slow" )
  }, 3000);

app/views/shared/_user_nav_bar.html.haml
.logo-wrapper
  = link_to root_path(display_mode: params[:display_mode]), class: 'd-flex' do
    = image_tag 'cdc.jpg', class: 'rounded-circle flex-grow-1'

.headerButtons.text-center
  %div{'data-toggle' => 'tooltip', title: "ព័ត៌មានទូទៅទាក់ទងនឹងជំងឺកូវីដ១៩"}
    = link_to faqs_path , class: "text-white" do
      %i.far.fa-question-circle{style: 'font-size: 20px;'}

  %div{'data-toggle' => 'tooltip', title: "Developer Guide"}
    = link_to developer_guides_path, class: "text-white" do
      %i.fas.fa-code

  .dropup.dropright{'data-toggle' => 'tooltip', title: t('shared.share')}
    %a{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown"}
      %i.fas.fa-share-square{style: 'font-size: 18px;'}

    .dropdown-menu.p-0
      = social_share_button_tag(t('shared.share_description'), :url => root_url, desc: t('shared.share_description'))

  %div{'data-toggle' => 'tooltip', title: t('shared.about')}
    = link_to about_path(display_mode: params[:display_mode]) do
      %i.fas.fa-info-circle{style: 'font-size: 20px;'}

  .visitor-wrapper.text-white{ 'data-toggle' => 'tooltip', title: t('shared.number_of_visitor') }
    %div
      %i.fas.fa-eye{style: 'font-size: 18px;'}
    .visitor= number_to_human(Ahoy::Visit.count, :format => '%n%u', :units => { :thousand => 'K' })