config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "welcome#index"
  devise_for :users, skip: [:registrations]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :reports, only: [:index, :new, :create]
  resources :videos, only: [:index, :new, :create]
  resources :sites, only: [:index, :new, :create]

  resource :about, only: [:show]

  resources :list_views, only: [:index]

  resources :developer_guides, only: [:index]

  resource :setting, except: [:destroy]
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  has_many :report_details, dependent: :destroy

  validates :location_code, presence: true
  validates :location_code, uniqueness: true
  validates :total_case, numericality: { greater_than_or_equal_to: 0 }
  validates :new_case, numericality: { greater_than_or_equal_to: 0 }
  validates :new_recovered_case, numericality: { greater_than_or_equal_to: 0 }
  validates :new_death_case, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :location, class_name: "Location", foreign_key: "location_code"

  def self.has_detail?
    ReportDetail.count > 0
  end
end

app/controllers/api/v1/reports_controller.rb
class Api::V1::ReportsController < ApplicationController
  def index
    reports = Report.includes(:location)
      .where('new_case > ? or new_recovered_case > ? or new_death_case > ?', 0, 0, 0)

    render json: reports, each_serializer: V1::ReportSerializer
  end

end

app/controllers/reports_controller.rb
class ReportsController < AdminController
  def index
    @cols = ReportDetail.order(display_order: :asc).pluck(:field_name).uniq
    @reports = Report.includes(:report_details)
  end

  def new
  end

  def create
    tempfile = file_params[:file]
    ::ReportImportService.process(tempfile.path)

    redirect_to reports_path, notice: "successfully imported"
  end

  private
    def file_params
      params.require(:reports).permit(:file)
    end
end

app/views/reports/index.html.erb
<div class="mt-3">
  <%= link_to "New reports", new_report_path, class: "btn btn-primary float-right" %>
  <h2>Reports: <b><%= @reports.count %></b></h2>
</div>

<%
  i = 0
  total_case = 0
  total_case = 0
  total_new_case = 0
  total_recovered_case = 0
  total_new_recovered_case = 0
  total_death_case = 0
  total_new_death_case = 0
%>

<table class="table">
  <tr>
    <th>#</th>
    <th>Location name</th>
    <th>Total case</th>
    <th>New case</th>
    <th>Recovered case</th>
    <th>New recovered case</th>
    <th>Death case</th>
    <th>New death case</th>
    <% @cols.each do |field| %>
      <th><%= field %></th>
    <% end %>
  </tr>

  <% @reports.each do |r| %>
    <%
      total_case += r.total_case
      total_new_case += r.new_case
      total_recovered_case += r.recovered_case
      total_new_recovered_case += r.new_recovered_case
      total_death_case += r.death_case
      total_new_death_case += r.new_death_case
    %>
    <tr>
      <td><%= i+=1 %></td>
      <td><%= r.location.try(:name_km) %></td>
      <td><%= r.total_case %></td>
      <td>
        <%if r.new_case > 0 %>
          <font color='blue'><%= r.new_case %></font>
        <% else %>
          -
        <% end %>
      </td>
      <td><%= r.recovered_case %></td>
      <td>
        <%if r.new_recovered_case > 0 %>
          <font color='green'><%= r.new_recovered_case %></font>
        <% else %>
          -
        <% end %>
      </td>
      <td><%= r.death_case %></td>
      <td>
        <%if r.new_death_case > 0 %>
          <font color='red'><%= r.new_death_case %></font>
        <% else %>
          -
        <% end %>
      </td>
      <% ReportDetail.where(report_id: r.id).each do |rd| %>
        <% @cols.each do |c| %>
          <% if rd.field_name == c %>
            <td><%= rd.field_value %></td>
          <% end %>
        <% end %>
      <% end %>
    </tr>
  <% end %>
  <tr>
    <td colspan=2><h3>Total:</h3></td>
    <td><h3><%= total_case %></h3></td>
    <td>
      <%if total_new_case > 0 %>
        <h3><font color='blue'><%= total_new_case %></font></h3>
      <% else %>
        -
      <% end %>
    </td>
    <td><h3><%= total_recovered_case %></h3></td>
    <td>
      <%if total_new_recovered_case > 0 %>
        <h3><font color='green'><%= total_new_recovered_case %></font></h3>
      <% else %>
        -
      <% end %>
    </td>
    <td><h3><%= total_death_case %></h3>
      
    </td>
    <td>
      <%if total_new_death_case > 0 %>
        <h3><font color='red'><%= total_new_death_case %></font></h3>
      <% else %>
        -
      <% end %>
    </td>
  </tr>
</table>

app/views/reports/new.html.haml
.d-flex.justify-content-center.align-items-center.vh-100
  .card
    .card-header 
      %h5 Choose reports
    .card-body
      = simple_form_for :reports, url: reports_path do |f|
        = f.input :file, as: :file, label: false
        = f.submit "Upload", class: "btn btn-primary"